# Generated by Django 3.2.7 on 2021-09-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_technology_recipe_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
