# Generated by Django 3.2.7 on 2021-09-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FilePathField(default='', path='myfile/recipe/static/images'),
        ),
    ]
